version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container-trading
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trading
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka-network

  app:
    build:
      context: .
    container_name: springboot-app-trading
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5457:5457"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trading?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: spring
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka-network

volumes:
  mysql_data:

networks:
  kafka-network:
    external: true
